### ISSUE TITLE
QR linux server or browser integration

### ISSUE THREAD

**Issue by Wedmal** [updatesvc/WhatsApee#1]
Good day. My Linux version doesn’t have a graphical interface. Can I get the QR-code from the browser?

**Comment by Wedmal** [comment]
![image](https://user-images.githubusercontent.com/48508154/54892783-72ae1780-4ee5-11e9-967c-4777091db3ee.png)

**Comment by Wedmal** [comment]
logs:
0 info it worked if it ends with ok                                                                                                                                       
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]                                                                                                                
2 info using npm@3.10.10                                                                                                                                                  
3 info using node@v6.16.0                                                                                                                                                 
4 verbose run-script [ 'prestart', 'start', 'poststart' ]                                                                                                                 
5 info lifecycle WhatsApee@1.0.0~prestart: WhatsApee@1.0.0                                                                                                                
6 silly lifecycle WhatsApee@1.0.0~prestart: no script for prestart, continuing                                                                                            
7 info lifecycle WhatsApee@1.0.0~start: WhatsApee@1.0.0                                                                                                                   
8 verbose lifecycle WhatsApee@1.0.0~start: unsafe-perm in lifecycle true                                                                                                  
9 verbose lifecycle WhatsApee@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/WhatsApee/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/
10 verbose lifecycle WhatsApee@1.0.0~start: CWD: /var/www/html/WhatsApee                                                                                                  
11 silly lifecycle WhatsApee@1.0.0~start: Args: [ '-c', 'electron .' ]                                                                                                    
12 silly lifecycle WhatsApee@1.0.0~start: Returned: code: 1  signal: null                                                                                                 
13 info lifecycle WhatsApee@1.0.0~start: Failed to exec start script                                                                                                      
14 verbose stack Error: WhatsApee@1.0.0 start: `electron .`                                                                                                               
14 verbose stack Exit status 1                                                                                                                                            
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)                                                                
14 verbose stack     at emitTwo (events.js:106:13)                                                                                                                        
14 verbose stack     at EventEmitter.emit (events.js:191:7)                                                                                                               
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)                                                                     
14 verbose stack     at emitTwo (events.js:106:13)                                                                                                                        
14 verbose stack     at ChildProcess.emit (events.js:191:7)                                                                                                               
14 verbose stack     at maybeClose (internal/child_process.js:920:16)                                                                                                     
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)                                                                             
15 verbose pkgid WhatsApee@1.0.0                                                                                                                                          
16 verbose cwd /var/www/html/WhatsApee                                                                                                                                    
17 error Linux 3.10.0-957.10.1.el7.x86_64                                                                                                                                 
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"                                                                                                                      
19 error node v6.16.0                                                                                                                                                     
20 error npm  v3.10.10                                                                                                                                                    
21 error code ELIFECYCLE                                                                                                                                                  
22 error WhatsApee@1.0.0 start: `electron .`                                                                                                                              
22 error Exit status 1                                                                                                                                                    
23 error Failed at the WhatsApee@1.0.0 start script 'electron .'.                                                                                                         
23 error Make sure you have the latest version of node.js and npm installed.                                                                                              
23 error If you do, this is most likely a problem with the WhatsApee package,
24 verbose exit [ 1, true ]

**Comment by ib0b** [comment]
Hi, whatsapee heavily relies on electron (Google Chrome based API) so your best bet is to install a virtual dispaly.
I haven't done this, but you should have some luck installing noMachine which is like RDP for linux. Then using nomachine you can view the QR code.

Also if you find error in running , its probably due to your linux not having the necessary packages for Electron. Installing google chrome via the commandline should resolve this issue

**Comment by Wedmal** [comment]
Thank. I run this script and it works. Is it possible to run this script without it?

**Comment by ib0b** [comment]
I don't think its possible without it.
